/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   CGenerator.cpp                                     :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: jikaewsi <strixz.self@gmail.com>           +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2025/12/13 01:26:45 by jikaewsi          #+#    #+#             */
/*   Updated: 2025/12/13 01:28:00 by jikaewsi         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "CGenerator.hpp"

#include <sstream>
#include <map>

std::string CGenerator::generateHeader(const LexerParser &parser) {

    std::stringstream ss;
    
    ss << "/* Generated by ft_lex */\n";
    ss << "#include <stdio.h>\n";
    ss << "#include <stdlib.h>\n";
    ss << "#include <string.h>\n\n";
    ss << "/* Definitions Section */\n";
    ss << parser.getDefinitions() << "\n\n";
    
    return ss.str();

}

std::string CGenerator::generateTables(const std::vector<DFA> &dfas, const LexerParser &parser) {
    std::stringstream ss;
    ss << "/* Start Conditions Definitions */\n";
    const auto& startConds = parser.getStartConditions();
    for (size_t i = 0; i < startConds.size(); ++i) {
        ss << "#define " << startConds[i].name << " " << i << "\n";
    }
    ss << "\n";

    ss << "/* DFA Tables */\n";
    size_t totalStates = 0;
    for (const auto& dfa : dfas) {
        totalStates += dfa.states.size();
    }
    
    std::map<int, int> idToIndex; // Global ID to Index (0 to totalStates-1)
    int currentIndex = 0;
    
    ss << "static const int yy_start_state_idx[" << dfas.size() << "] = {\n    ";
    for (const auto& dfa : dfas) {
        // Find the index of the start state for this DFA
        // The start state is the first one generated usually, but to be sure:
        // Actually, we just map everything sequentially. We must ensure dfa.start->id is what we index.
        // Wait, dfa.start is just ONE of the states in dfa.states.
        // Let's populate idToIndex first:
        for (const auto& state : dfa.states) {
            idToIndex[state->id] = currentIndex++;
        }
    }
    
    for (const auto& dfa : dfas) {
        ss << idToIndex[dfa.start->id] << ", ";
    }
    ss << "\n};\n\n";
    
    // Transition Table: C array format
    ss << "static const int yy_nxt[" << totalStates << "][258] = {\n";
    for (const auto& dfa : dfas) {
        for (const auto& state : dfa.states) {
            ss << "    {";
            for (int c = 0; c < 258; ++c) {
                int nextIdx = -1;
                if (state->transitions.count(c)) {
                    nextIdx = idToIndex[state->transitions.at(c)->id];
                }
                ss << nextIdx << ",";
            }
            ss << "},\n";
        }
    }
    ss << "};\n\n";

    // Accepting State Table: C array format
    ss << "static const int yy_accept[" << totalStates << "] = {\n    ";
    for (const auto& dfa : dfas) {
        for (const auto& state : dfa.states) {
            if (state->isAccepting) {
                ss << state->priority << ", ";
            } else {
                ss << "-1, ";
            }
        }
    }
    ss << "\n};\n\n";

    // Trailing Context Boundary Table: 1 = boundary (end of r1), -1 = none
    ss << "static const int yy_trailing_ctx[" << totalStates << "] = {\n    ";
    for (const auto& dfa : dfas) {
        for (const auto& state : dfa.states) {
            ss << (state->trailingContextBoundary ? 1 : -1) << ", ";
        }
    }
    ss << "\n};\n\n";

    return ss.str();
}

// Public interface (calls helper)
std::string CGenerator::generateLexerBody(const LexerParser &parser) {
    return _generateRulesSwitch(parser);
}

// Generates the C switch-case block for rule actions
std::string CGenerator::_generateRulesSwitch(const LexerParser &parser) {
    std::stringstream ss;
    const auto &rules = parser.getRulesList();
    for (size_t i = 0; i < rules.size(); ++i) {
        // C-specific switch/case syntax
        ss << "                case " << i << ":\n";
        ss << "                    " << rules[i].action << "\n";
        ss << "                    break;\n";
    }
    return ss.str();
}

std::string CGenerator::generateUserCode(const LexerParser &parser) {
    std::stringstream ss;
    ss << "\n/* User Code Section */\n";
    ss << parser.getUserCode() << "\n";
    return ss.str();
}

std::string CGenerator::generateEofActions(const LexerParser &parser) {
    std::stringstream ss;
    const auto &eofActions = parser.getEofActions();

    if (!eofActions.empty()) {
        ss << "            switch (yy_start) {\n";
        for (const auto& [condIdx, action] : eofActions) {
            ss << "                case " << condIdx << ": {\n";
            ss << "                    " << action << "\n";
            ss << "                    break;\n";
            ss << "                }\n";
        }
        ss << "            }\n";
    }
    return ss.str();
}
