/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   PythonGenerator.cpp                                :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: jikaewsi <strixz.self@gmail.com>           +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2025/12/13 01:30:45 by jikaewsi          #+#    #+#             */
/*   Updated: 2026/03/14 11:58:01 by jikaewsi         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "../include/PythonGenerator.hpp"

#include <map>
#include <sstream>
#include <algorithm>

static std::string _cleanAction(std::string action) {
    size_t s = action.find_first_not_of(" \t\n\r");
    if (s != std::string::npos) {
        action = action.substr(s);
        if (action[0] == '{') action = action.substr(1);
    }
    size_t e = action.find_last_not_of(" \t\n\r");
    if (e != std::string::npos) {
        action = action.substr(0, e + 1);
        if (!action.empty() && action.back() == '}') action.pop_back();
    }
    s = action.find_first_not_of(" \t\n\r");
    e = action.find_last_not_of(" \t\n\r");
    if (s != std::string::npos && e != std::string::npos) {
        action = action.substr(s, e - s + 1);
    } else {
        action = "pass";
    }

    // Replace yytext/yyleng with self.yytext/self.yyleng
    size_t pos = 0;
    while ((pos = action.find("yytext", pos)) != std::string::npos) {
        if (pos == 0 || (!std::isalnum(action[pos-1]) && action[pos-1] != '_')) {
            action.replace(pos, 6, "self.yytext");
            pos += 11;
        } else pos += 6;
    }
    pos = 0;
    while ((pos = action.find("yyleng", pos)) != std::string::npos) {
        if (pos == 0 || (!std::isalnum(action[pos-1]) && action[pos-1] != '_')) {
            action.replace(pos, 6, "self.yyleng");
            pos += 11;
        } else pos += 6;
    }

    return action;
}

std::string PythonGenerator::generateHeader(const LexerParser &parser) {
  std::stringstream ss;
  ss << "# Generated by ft_lex\nimport sys\nimport re\n\n";
  ss << "# Definitions Section\n" << parser.getDefinitions() << "\n\n";
  return ss.str();
}

std::string PythonGenerator::generateTables(const std::vector<DFA> &dfas, const LexerParser &parser) {
  std::stringstream ss;
  ss << "    # DFA Tables\n";
  const auto &startConds = parser.getStartConditions();
  for (size_t i = 0; i < startConds.size(); ++i)
    ss << "    " << startConds[i].name << " = " << i << "\n";
  ss << "\n    YY_START_STATE_IDX = [";
  int stateOffset = 0;
  for (const auto &dfa : dfas) { ss << stateOffset << ", "; stateOffset += dfa.states.size(); }
  ss << "]\n\n";

  std::map<int, int> idToIndex;
  int currentIndex = 0;
  for (const auto &dfa : dfas) { for (const auto &state : dfa.states) idToIndex[state->id] = currentIndex++; }

  ss << "    YY_NXT = [\n";
  for (const auto &dfa : dfas) {
    for (const auto &state : dfa.states) {
      ss << "        [";
      for (int c = 0; c < 258; ++c) {
        int nextIdx = -1;
        if (state->transitions.count(c)) nextIdx = idToIndex[state->transitions.at(c)->id];
        ss << nextIdx << ",";
      }
      ss << "],\n";
    }
  }
  ss << "    ]\n\n    YY_ACCEPT = [\n        ";
  for (const auto &dfa : dfas) {
    for (const auto &state : dfa.states) {
      if (state->isAccepting) ss << state->priority << ", ";
      else ss << "-1, ";
    }
  }
  ss << "\n    ]\n\n";
  return ss.str();
}

std::string PythonGenerator::generateLexerBody(const LexerParser &parser) {
  std::stringstream ss;
  const auto &rules = parser.getRulesList();

  // Generate Match Action Methods
  for (size_t i = 0; i < rules.size(); ++i) {
    ss << "    def _action_" << i << "(self):\n";
    std::string action = _cleanAction(rules[i].action);
    std::istringstream stream(action);
    std::string line;
    while (std::getline(stream, line)) ss << "        " << line << "\n";
    ss << "\n";
  }

  // Generate Switch logic in yylex
  ss << "    def _do_action(self, match_id):\n";
  for (size_t i = 0; i < rules.size(); ++i) {
    if (i == 0) ss << "        if match_id == " << i << ": return self._action_" << i << "()\n";
    else ss << "        elif match_id == " << i << ": return self._action_" << i << "()\n";
  }
  ss << "        return None\n";

  return ss.str();
}

std::string PythonGenerator::generateUserCode(const LexerParser &parser) {
  std::stringstream ss;
  ss << "\n# User Code Section\n" << parser.getUserCode() << "\n";
  return ss.str();
}

std::string PythonGenerator::generateEofActions(const LexerParser &parser) {
  std::stringstream ss;
  const auto &eofActions = parser.getEofActions();

  for (auto const& [condIdx, action] : eofActions) {
    ss << "    def _eof_action_" << condIdx << "(self):\n";
    std::string cleaned = _cleanAction(action);
    std::istringstream stream(cleaned);
    std::string line;
    while (std::getline(stream, line)) ss << "        " << line << "\n";
    ss << "\n";
  }

  ss << "    def _do_eof_action(self, cond_idx):\n";
  bool first = true;
  for (auto const& [condIdx, action] : eofActions) {
    if (first) ss << "        if cond_idx == " << condIdx << ": return self._eof_action_" << condIdx << "()\n";
    else ss << "        elif cond_idx == " << condIdx << ": return self._eof_action_" << condIdx << "()\n";
    first = false;
  }
  ss << "        return None\n";

  return ss.str();
}
